FROM alpine

# Set environment variables for uid, gid, and umask
ENV UID=1000
ENV GID=1000
ENV UMASK=022
ENV USERNAME=spiritapp

# Change the repository mirror and install required packages
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
    apk upgrade --update-cache && \
    apk add openjdk8 && \
    apk add ffmpeg && \
    rm -rf /tmp/* /var/cache/apk/*

# Create a user and group with the specified uid and gid
RUN addgroup -g $GID $USERNAME && \
    adduser -D -u $UID -G $USERNAME $USERNAME

# Set umask
RUN umask $UMASK

VOLUME ["/tmp","/app"]
COPY db /home/$USERNAME/db/
RUN mkdir -p /app/resources
ADD spirit-0.0.1-SNAPSHOT.jar app.jar

# Switch to the specified user
USER $USERNAME

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar","--spring.profiles.active=docker"]
